### ISSUE TITLE
Autocomplete for friends not working

### ISSUE THREAD

**Issue by JimB99** [Sk1erLLC/Hypixel-Autocomplete-Mod#2]
For some reason the autocomplete does not work if the friends are not in the same lobby anymore. It used to work up until a few weeks ago, I even tried reinstalling it, but still nothing. Any idea why it could be?

**Comment by Sychic** [comment]
Hey, This is because we finally deprecated our cached friends API because of hypixel's decision to remove the friends endpoint. Unfortunately, there is nothing we can do about this, nor do we plan to try to bring it back.

**Comment by JimB99** [comment]
oh okay, thank you for your super quick reply!
